openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080/
    description: Generated server url
paths:
  /vendors/update/{vaccineid}/{vendorid}:
    post:
      tags:
        - vendor-controller
      operationId: updateVaccineStock
      parameters:
        - name: vaccineid
          in: path
          required: true
          schema:
            type: string
        - name: vendorid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /vendors/{vaccineid}/{vendorid}:
    get:
      tags:
        - vendor-controller
      operationId: getListByVaccinesVendors
      parameters:
        - name: vaccineid
          in: path
          required: true
          schema:
            type: string
        - name: vendorid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vaccines'
  /vendors/vendorId/{vendorid}:
    get:
      tags:
        - vendor-controller
      operationId: getListByVendorId
      parameters:
        - name: vendorid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vaccines'
  /vendors/vaccineId/{vaccineid}:
    get:
      tags:
        - vendor-controller
      operationId: getListByVaccineId
      parameters:
        - name: vaccineid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vaccines'
components:
  schemas:
    Vaccines:
      type: object
      properties:
        vaccine_id:
          type: string
        vendor_id:
          type: string
        vaccine_name:
          type: string
        available_count:
          type: integer
          format: int32
        exp_date:
          type: string
          format: date-time
